# Generated by Django 5.1.15 on 2026-07-18 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название модели')),
            ],
            options={
                'verbose_name': 'Модель оборудования',
                'verbose_name_plural': 'Модели оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('component_type', models.CharField(blank=True, help_text='Резистор, конденсатор, транзистор и т.д.', max_length=100, verbose_name='Тип компонента')),
                ('resistance', models.CharField(blank=True, max_length=50, verbose_name='Сопротивление')),
                ('power', models.CharField(blank=True, max_length=50, verbose_name='Мощность')),
                ('voltage', models.CharField(blank=True, max_length=50, verbose_name='Напряжение')),
                ('current', models.CharField(blank=True, max_length=50, verbose_name='Ток')),
                ('capacitance', models.CharField(blank=True, max_length=50, verbose_name='Ёмкость')),
                ('current_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Текущий остаток')),
                ('min_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Минимальный остаток')),
                ('lead_time_days', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Срок поставки (дней)')),
                ('preferred_supplier', models.CharField(blank=True, max_length=255, verbose_name='Предпочтительный поставщик')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Радиодеталь',
                'verbose_name_plural': 'Радиодетали',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('warehouse', 'Кладовщик'), ('repair_manager', 'Менеджер по ремонту'), ('accountant', 'Бухгалтер')], default='repair_manager', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('current_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='Текущий заказчик')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipmentmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Номер заказа')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='Дата приёма')),
                ('initial_condition', models.TextField(blank=True, verbose_name='Начальное состояние')),
                ('fault_description', models.TextField(blank=True, verbose_name='Описание неисправности')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('seal_numbers', models.CharField(blank=True, max_length=255, verbose_name='Номера пломб')),
                ('shipping_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('shipping_company', models.CharField(blank=True, max_length=100, verbose_name='Транспортная компания')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость ремонта')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер счёта')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен')], default='unpaid', max_length=20, verbose_name='Статус оплаты')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('diagnostic', 'Диагностика'), ('repair', 'Ремонт'), ('ready_for_shipment', 'Готов к отгрузке'), ('shipped', 'Отгружен')], default='accepted', max_length=20, verbose_name='Статус')),
                ('yandex_disk_folder', models.URLField(blank=True, verbose_name='Папка на Яндекс.Диске')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client', verbose_name='Заказчик')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заказ на ремонт',
                'verbose_name_plural': 'Заказы на ремонт',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('diagnostic', 'Диагностика'), ('repair', 'Ремонт'), ('ready_for_shipment', 'Готов к отгрузке'), ('shipped', 'Отгружен')], max_length=20, verbose_name='Статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.repairorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.repairorder', verbose_name='Заказ')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sparepart', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Деталь в заказе',
                'verbose_name_plural': 'Детали в заказе',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата движения')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('movement_type', models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход')], max_length=10, verbose_name='Тип движения')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.sparepart', verbose_name='Деталь')),
                ('repair_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repairorder', verbose_name='Заказ на ремонт')),
            ],
            options={
                'verbose_name': 'Движение запчасти',
                'verbose_name_plural': 'Движения запчастей',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='StorageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер кассетницы')),
                ('row_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер ряда')),
                ('cell_row', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер ячейки в ряду')),
                ('part', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_cell', to='core.sparepart', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Ячейка хранения',
                'verbose_name_plural': 'Ячейки хранения',
                'ordering': ['cabinet_number', 'row_number', 'cell_row'],
                'unique_together': {('cabinet_number', 'row_number', 'cell_row')},
            },
        ),
    ]
